### ISSUE TITLE
Search into the url also

### ISSUE THREAD

**Issue by humitos** [emacs-helm/helm-firefox#4]
One of the things that I love from Firefox is that in the url toolbar you can start typing and you always get what you want because it searches into the: history and bookmarks considering the title of the page and also its url.

`helm-firefox` is really cool, but it would be amazing if it could work in the same way that the firefox url search bar. Maybe history is not so easy to implement, but at least add the url in the query would be great!

An example:

Search in Firefox:

![screenshot - 020616 - 00 13 54](https://cloud.githubusercontent.com/assets/244656/15734621/411bdbce-2857-11e6-8c86-c91d0779a5ae.png)

Search in helm-firefox using `helm-firefox-bookmarks`

![screenshot - 020616 - 00 15 02](https://cloud.githubusercontent.com/assets/244656/15734617/353486d0-2857-11e6-843d-ced7b512c7e5.png)
![screenshot - 020616 - 00 15 33](https://cloud.githubusercontent.com/assets/244656/15734618/37ba2a90-2857-11e6-9f3a-a737f42d950b.png)

Is that possible?

**Comment by thierryvolpiatto** [comment]
Sorry for late reply.

Manuel Kaufmann notifications@github.com writes:

> Is that possible?

Yes, something like this should work:

diff --git a/helm-firefox.el b/helm-firefox.el
index cf7e5cd..af6559b 100644
--- a/helm-firefox.el
+++ b/helm-firefox.el
@@ -122,6 +122,10 @@ On Mac OS X, probably set to \"~/Library/Application Support/Firefox/\"."
                              (helm-guess-firefox-bookmark-file)
                              helm-firefox-bookmark-url-regexp
                              helm-firefox-bookmarks-regexp))))
-    :match (lambda (candidate)
-             (or (helm-mm-match candidate)
-                 (helm-mm-match (helm-firefox-bookmarks-get-value
-                                 candidate))))
   :candidates (lambda ()
                 (mapcar #'car helm-firefox-bookmarks-alist))
   :filtered-candidate-transformer

I will try to add this feature ASAP.

Thanks.

## 

Thierry

**Comment by humitos** [comment]
Nice! It seems to work as I expected! Thanks a lot!

I think we should keep thinking on the way of showing the results, because with that code once you are filtering the bookmarks you don't see the part of the URL matching, so it could be confusing in some way.

In other helm buffers you can see, for example, the path of the file and the line with its content; both things highlighted on the matching (similar to what you see in the Firefox screenshot, although it uses 2 lines -the title and the url)

**Comment by thierryvolpiatto** [comment]
Manuel Kaufmann notifications@github.com writes:

> Nice! It seems to work as I expected! Thanks a lot!
> 
> I think we should keep thinking on the way of showing the results,
> because with that code once you are filtering the bookmarks you don't
> see the part of the URL matching, so it could be confusing in some
> way.

Yes, it is a one minute patch, I will try to provide something better
ASAP.

> In other helm buffers you can see, for example, the path of the file
> and the line with its content; both things highlighted on the matching
> (similar to what you see in the Firefox screenshot, although it uses 2
> lines -the title and the url)

We can use two lines, no problem.

## 

Thierry

**Comment by thierryvolpiatto** [comment]
![screenshot - 11062016 - 13 56 34](https://cloud.githubusercontent.com/assets/1533939/15984940/6e60993a-2fdc-11e6-80b2-cb7771b06312.png)
